id=ga.standard
version=2.0
family=evolutionary
stages=initialize,select,recombine,mutate,evaluate,update,measure,stop
strategy.selection=tournament
strategy.update=single-objective-elitist
requirements=one-or-more-objectives
