source.ideaflow.jar = src/
bin.includes = plugin.xml,\
               META-INF/,\
               ideaflow.jar,\
               LICENSE,\
               NOTICE,\
               CHANGELOG.md,\
               src/org/ideaflow/default.png
