source.ideaflow.jar = src/
bin.includes = plugin.xml,\
               META-INF/,\
               ideaflow.jar,\
               LICENSE,\
               NOTICE,\
               README.md,\
               CHANGELOG.md,\
               docs/
